### PR TITLE
Fix dynamically allocated shape matrices

### LINKED ISSUE #987: Assertion failure in Element test
```
[----------] 2 tests from NumLibFunctionInterpolationTest
[ RUN      ] NumLibFunctionInterpolationTest.TwoVariablesTwoNodes
[       OK ] NumLibFunctionInterpolationTest.TwoVariablesTwoNodes (0 ms)
[ RUN      ] NumLibFunctionInterpolationTest.Linear1DElement
testrunner: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:378: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Abgebrochen (Speicherabzug geschrieben)
```

I compiled it using dynamically allocated Eigen matrices.

### PR DESCRIPTION
**Pull request by chleh**
This PR fixes #987 and therefore is a precursor to #988.

The error causing #987 was a forgotten call to `resize()` in the setup of the test. In order to rule out such errors, in this PR the default constructor of the `ShapeMatrices` struct has been deleted along with the `resize()` methods. Therefore `ShapeMatrices` now always have to be given the correct size upon construction.

Deleting the default constuctor entails minor changes in GWFlow and NeumannBCs.

Additionally a new `cpp` file has been added in order to prevent some linker error.

### CODE REVIEW

File: NumLib/Fem/CoordinatesMapping/ShapeMatrices.h [hunk 1]
```diff
@@ -58,11 +58,14 @@ struct ShapeMatrices
     JacobianType invJ;  ///< Inverse matrix of the Jacobian
     DxShapeType dNdx;   ///< Matrix of gradient of shape functions in physical coordinates, dN(r)/dx
 
-    /** The default constructor is used by fixed-size (at compile-time)
-     * matrix/vector types where no resizing of the matrices/vectors is required
-     * in this constructor.
+    /** Not default constructible, dimensions always must be given.
+     *
+     * The default constructor has been deleted expplicitly, because with
```
Comment (endJunction) [inline NumLib/Fem/CoordinatesMapping/ShapeMatrices.h]: Typo: explicitly

File: NumLib/Fem/ShapeFunction/ShapeStaticConsts.cpp [hunk 2]
```diff
@@ -0,0 +1,92 @@
+/**
+ * \file ShapeStaticConsts.cpp
+ *
+ * \copyright
+ * Copyright (c) 2012-2016, OpenGeoSys Community (http://www.opengeosys.org)
+ *            Distributed under a Modified BSD License.
+ *              See accompanying file LICENSE.txt or
+ *              http://www.opengeosys.org/project/license
+ *
+ * The purpose of this file is to preven linker errors.
```
Comment (endJunction) [inline NumLib/Fem/ShapeFunction/ShapeStaticConsts.cpp]: Typo: prevent.

**Comment by endJunction** [comment]
:fast_forward:

**Comment by TomFischer** [comment]
:fast_forward:
