### PR TITLE
Tools for Neumann boundary condition preparation

### LINKED ISSUE #992: Bug in ComputeSurfaceNodeIDsInPolygonalRegion
The tool is used to compute a text file containing a table with two columns. The first column contains the node id of the node within the subsurface mesh, the second column contains the associated area. The file is used as an input (direct boundary condition) in the OGS-5 simulator.

The bug is: A incorrect area is computed for border nodes.

### PR DESCRIPTION
**Pull request by TomFischer**
This PR consists of two new simple tools
 - ExtractSurface
 - ComputeNodeAreasFromSurfaceMesh
and some additional functionality to the already existing tool ResetPropertyInPolygonalRegion.

The tools can be used in a workflow setting Neumann boundary conditions for different regions of the top surface (for instance groundwater recharge):
 1. Extract top surface (ExtractSurface)
 2. Mark the surface elements in the region the Neumann conditions should be set: ResetPropertyInPolygonalRegion
 3. Remove those parts of the surface mesh the Neumann condition shouldn't be set to deploying the tool removeMeshElements which results in a surface patch
 4. For OGS-5 modelling use the surface patch to generate Neumann condition using the tool ComputeNodeAreasFromSurfaceMesh

Using this workflow the bug described in issue #992 should be corrected.
Fixes #992.

### CODE REVIEW

File: Applications/Utils/MeshEdit/ExtractSurface.cpp [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+	cmd.parse(argc, argv);
+
+	std::unique_ptr<MeshLib::Mesh const> mesh(
+	    FileIO::readMeshFromFile(mesh_in.getValue()));
+	INFO("Mesh read: %u nodes, %u elements.", mesh->getNNodes(), mesh->getNElements());
+
+	// extract top surface
+	MathLib::Vector3 const dir(0.0, 0.0, -1.0);
+	double const angle(90);
```
Comment (endJunction) [inline Applications/Utils/MeshEdit/ExtractSurface.cpp]: I'd add the direction (with default 0,0,-1) and the angle (with default value 90) to the command line arguments. Otherwise the tool should be named 'extractTopSurface'.

File: Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp [hunk 2]
```diff
@@ -224,6 +224,18 @@ int main (int argc, char* argv[])
...
 	if (int_property_arg.isSet()) {
 		int int_property_val(int_property_arg.getValue());
+
+		// check if PropertyVector exists
+		boost::optional<MeshLib::PropertyVector<int> &> opt_pv(
+			mesh->getProperties().getPropertyVector<int>(property_name)
+		);
+		if (!opt_pv) {
+			opt_pv = mesh->getProperties().createNewPropertyVector<int>(
+				property_name, MeshLib::MeshItemType::Cell, 1);
```
Comment (endJunction) [inline Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp]: The tuple size is 1 by default...
I had to ask myself what is so special about the 1 in the code...

File: Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+		std::abort();
+	}
+
+	ids_and_area_out << std::setprecision(20);
+	csv_out << std::setprecision(20);
+
+	ids_and_area_out << ids_and_areas[0].first << " " << ids_and_areas[0].second;
+	csv_out << "ID x y z area node_id\n"; // CSV header
+	csv_out << 0 << " " << *(mesh_nodes[0])
+			<< ids_and_areas[0].second << " " << ids_and_areas[0].first;
```
Comment (endJunction) [inline Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp]: I do overlook something probably. Why is the output for id=0 not in the for-loop below? The loop starts from 1.

File: Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+#include "BaseLib/FileTools.h"
+
+#include "FileIO/readMeshFromFile.h"
+#include "FileIO/readGeometryFromFile.h"
+
+#include "MeshLib/Mesh.h"
+#include "MeshLib/Node.h"
+#include "MeshLib/MeshSurfaceExtraction.h"
+
+void writeToFile(std::string const& id_area_fname, std::string const& csv_fname,
```
Comment (endJunction) [inline Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp]: Please add static to this function. Otherwise there is a missing prototype warning.

File: Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+	}
+
+	std::vector<double> areas(
+	    MeshLib::MeshSurfaceExtraction::getSurfaceAreaForNodes(*surface_mesh));
+
+	// pack area and node id together
+	std::vector<std::pair<std::size_t, double>> ids_and_areas;
+	for (std::size_t k(0); k<areas.size(); ++k) {
+		ids_and_areas.push_back(std::make_pair((*orig_node_ids)[k], areas[k]));
+	}
```
Comment (endJunction) [inline Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp]: Can be written w/o for-loop:
```c++
std::transform(orig_node_ids->begin(), orig_node_ids->end(), areas.begin(),
	               std::back_inserter(ids_and_areas),
	               std::make_pair<std::size_t const&, double const&>);
```

File: MeshLib/MeshGenerators/VtkMeshConverter.cpp [hunk 6]
```diff
@@ -455,6 +456,12 @@ void VtkMeshConverter::convertArray(vtkDataArray &array, MeshLib::Properties &pr
 		return;
 	}
 
+	if (vtkUnsignedLongArray::SafeDownCast(&array))
+	{
+		VtkMeshConverter::convertTypedArray<std::size_t>(array, properties, type);
```
Comment (endJunction) [inline MeshLib/MeshGenerators/VtkMeshConverter.cpp]: std::size_t -> unsigned long.
I'm not sure about the correctness of the assumption that std::size_t is always an unsigned long.

Comment (TomFischer) [inline MeshLib/MeshGenerators/VtkMeshConverter.cpp]: The assumption that `std::size_t` is equal to `unsigned long` is **not** always fulfilled. As far as I know the C++ standard does not specify the size of `std::size_t` nor does it specify the size of `unsigned long`. Is an vtk unsigned long garantied to be equal to a compiler and architecture dependend `unsigned long`? What is the correct vtk type for storing `std::size_t`?

**Comment by bilke** [comment]
Maybe you can add a documentation page for the described workflow on docs.ogs.
