### PR TITLE
Fix material ID issues with line elements in GMSH import

### LINKED ISSUE #1074: Physical group IDs in GMSH
it seems GMSH2OGS is not correctly converting physical IDs to OGS material IDs. Is this a bug or an intended behavior?

### PR DESCRIPTION
**Pull request by norihiro-w**
This PR closes the issue #1074 by introducing the following changes
- fix a bug (?) that material IDs for line elements are always set zero
- condense material IDs after reading a GMSH mesh file.  

closes #1074

### CODE REVIEW

**Comment by TomFischer** [comment]
Looks good. :fast_forward:

File: FileIO/GMSHInterface.cpp [hunk 1]
```diff
@@ -235,6 +236,9 @@ MeshLib::Mesh* GMSHInterface::readGMSHMesh(std::string const& fname)
 		material_ids.insert(material_ids.end(), materials.cbegin(),
 			materials.cend());
 	}
+
+	MeshLib::ElementValueModification::condense(*mesh);
```
Comment (chleh) [inline FileIO/GMSHInterface.cpp]: Onyl curious: What is the condense good for?

**Comment by chleh** [comment]
:+1:

File: FileIO/GMSHInterface.cpp (hunk 1 above)
Comment (norihiro-w) [inline FileIO/GMSHInterface.cpp]: In Gmsh, material IDs are not necessary to start from zero and be continuous. e.g. it can be 1, 3, 6. but in ogs we need to change it to 0, 1, 2

Comment (chleh) [inline FileIO/GMSHInterface.cpp]: Thanks for the explanation.

**Comment by norihiro-w** [comment]
@chleh why is "rebase" needed? There is no conflicts as GitHub says...

**Comment by chleh** [comment]
I didn't want to say that you have to rebase. The label "rebase and merge" has been used recently with the meaning "rebase if necessary, possibly squashing some commits, and then merge", or "ready for merge". Maybe the true meaning has to be clarified, or we rename the label.
So: Feel free to merge!

**Comment by norihiro-w** [comment]
Jenkins failed in PETSc tests and it's nothing to do with this PR.

**Comment by chleh** [comment]
PETSc tests fail since #1050 and will do so until #1060 will be merged. Go ahead.

**Comment by norihiro-w** [comment]
thanks for the info
