### PR TITLE
Disable eigen vectorization by default.

### LINKED ISSUE #1881: Ehlers Damage test failing sporadically
Symptom: `ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension` sometimes falies (roughly 50% of the time)
```
[8] lehmannc@envinf141l:build-release-eigenlis$ OMP_NUM_THREADS=1 ctest -R ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
Test project /home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-eigenlis
    Start 210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
1/2 Test #210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension ...........***Failed    9.26 sec
    Start 211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff
2/2 Test #211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff ...***Failed    0.05 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   9.33 sec

The following tests FAILED:
	210 - ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension (Failed)
	211 - ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff (Failed)
Errors while running CTest
[8] lehmannc@envinf141l:build-release-eigenlis$ OMP_NUM_THREADS=1 ctest -R ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
Test project /home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-eigenlis
    Start 210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
1/2 Test #210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension ...........***Failed    9.42 sec
    Start 211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff
2/2 Test #211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff ...***Failed    0.05 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   9.50 sec

The following tests FAILED:
	210 - ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension (Failed)
	211 - ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff (Failed)
Errors while running CTest
[8] lehmannc@envinf141l:build-release-eigenlis$ OMP_NUM_THREADS=1 ctest -R ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
Test project /home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-eigenlis
    Start 210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
1/2 Test #210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension ...........***Failed    0.38 sec
    Start 211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff
2/2 Test #211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff ...***Failed    0.03 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.43 sec

The following tests FAILED:
	210 - ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension (Failed)
	211 - ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff (Failed)
Errors while running CTest
[8] lehmannc@envinf141l:build-release-eigenlis$ OMP_NUM_THREADS=1 ctest -R ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
Test project /home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-eigenlis
    Start 210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension
1/2 Test #210: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension ...........   Passed   10.72 sec
    Start 211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff
2/2 Test #211: ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension-vtkdiff ...   Passed    0.05 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =  10.79 sec
```

Probably this is linked to the following compiler warnings: (gcc 7.1.1, dynamic shape matrices):
```
[ 63%] Building CXX object MaterialLib/CMakeFiles/MaterialLib.dir/SolidModels/Ehlers.cpp.o
In file included from /home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.cpp:10:0:
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.h: In instantiation of ‘std::unique_ptr<typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables> MaterialLib::Solids::Lubby2::Lubby2<DisplacementDim>::createMaterialStateVariables() [with int DisplacementDim = 2; typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables = MaterialLib::Solids::MechanicsBase<2>::MaterialStateVariables]’:
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.cpp:19:16:   required from here
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.h:160:13: warning: ‘new’ of type ‘MaterialLib::Solids::Lubby2::Lubby2<2>::MaterialStateVariables’ with extended alignment 32 [-Waligned-new=]
             new MaterialStateVariables};
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.h:160:13: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.h:160:13: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
In file included from /home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.cpp:11:0:
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2-impl.h: In instantiation of ‘boost::optional<std::tuple<Eigen::Matrix<double, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, 1, 0, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, 1>, std::unique_ptr<typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables, std::default_delete<typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables> >, Eigen::Matrix<double, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, 1, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value> > > MaterialLib::Solids::Lubby2::Lubby2<DisplacementDim>::integrateStress(double, const ProcessLib::SpatialPosition&, double, const KelvinVector&, const KelvinVector&, const KelvinVector&, const typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables&) [with int DisplacementDim = 2; typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables = MaterialLib::Solids::MechanicsBase<2>::MaterialStateVariables; MaterialLib::Solids::Lubby2::Lubby2<DisplacementDim>::KelvinVector = Eigen::Matrix<double, 4, 1>]’:
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2.cpp:19:16:   required from here
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2-impl.h:191:13: warning: ‘new’ of type ‘MaterialLib::Solids::Lubby2::Lubby2<2>::MaterialStateVariables’ with extended alignment 32 [-Waligned-new=]
             new MaterialStateVariables{state}},
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2-impl.h:191:13: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Lubby2-impl.h:191:13: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
In file included from /home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Ehlers.cpp:11:0:
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Ehlers-impl.h: In instantiation of ‘boost::optional<std::tuple<Eigen::Matrix<double, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, 1, 0, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, 1>, std::unique_ptr<typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables, std::default_delete<typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables> >, Eigen::Matrix<double, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, 1, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value, ProcessLib::KelvinVectorDimensions<DisplacementDim>::value> > > MaterialLib::Solids::Ehlers::SolidEhlers<DisplacementDim>::integrateStress(double, const ProcessLib::SpatialPosition&, double, const KelvinVector&, const KelvinVector&, const KelvinVector&, const typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables&) [with int DisplacementDim = 2; typename MaterialLib::Solids::MechanicsBase<DisplacementDim>::MaterialStateVariables = MaterialLib::Solids::MechanicsBase<2>::MaterialStateVariables; MaterialLib::Solids::Ehlers::SolidEhlers<DisplacementDim>::KelvinVector = Eigen::Matrix<double, 4, 1>]’:
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Ehlers.cpp:19:16:   required from here
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Ehlers-impl.h:738:13: warning: ‘new’ of type ‘MaterialLib::Solids::Ehlers::StateVariables<2>’ with extended alignment 32 [-Waligned-new=]
             new StateVariables<DisplacementDim>{
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 static_cast<StateVariables<DisplacementDim> const&>(state)}},
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Ehlers-impl.h:738:13: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/lehmannc/prog/ogs6/github-chleh-PRs/src/MaterialLib/SolidModels/Ehlers-impl.h:738:13: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
```

Because adding `add_definitions(-DEIGEN_DONT_VECTORIZE)` to the main `CMakeLists.txt` fixes this problem: Now `$ OMP_NUM_THREADS=1 ctest --repeat-until-fail 50 -j 3 -R ogs-Mechanics_PlasticModel_SDED_Ehlers_Damage_UniaxialTension` just runs fine.

@endJunction noticed that in some classes `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` is missing.

This problem adds to a set of seven issues or pull requests regarding Eigen alignment: #743, #1221, #1250, #1323, #1483, #1684, #1760. Maybe we should consider disabling Eigen alignment entirely (at least by default).
Additionally, the warnings above are generated only with very recent compiler versions (cf. https://gcc.gnu.org/gcc-7/changes.html). So the average user might not get notified of the indicated problem.

### PR DESCRIPTION
**Pull request by endJunction**
This needs testing on local machines ( @chleh @fparisio ).
Hopefully
fixes #1881

### CODE REVIEW

File: Tests/NumLib/TestComponentNorms.cpp [hunk 1]
```diff
@@ -143,7 +143,7 @@ TEST(MPITest_NumLib, ComponentNormMultiComponent1)
     unsigned const num_components = 3;
     auto const norm_type = MathLib::VecNormType::NORM1;
     auto const tolerance =
-        num_components * 600 * std::numeric_limits<double>::epsilon();
```
Comment (chleh) [inline Tests/NumLib/TestComponentNorms.cpp]: This is strange. Without vectorization I'd assume that the situation becomes better. But the resulting tolerance is still OK.

File: CMakeLists.txt [hunk 2]
```diff
@@ -88,6 +88,7 @@ option(OGS_USE_PETSC "Use PETSc routines" OFF)
 option(OGS_USE_EIGEN "Use Eigen linear solver" ON)
 option(OGS_USE_EIGEN_UNSUPPORTED "Use Eigen unsupported modules" ON)
 option(EIGEN_NO_DEBUG "Disables Eigen's assertions" OFF)
+option(EIGEN_DONT_VECTORIZE "Disables explicit vectorization when defined." ON)
```
Comment (chleh) [inline CMakeLists.txt]: I'd write:
```
# We assume that it's save to use vectorization with Eigen < 3.3 (strictly smaller than 3.3.!).
# At least we only observed vectorization issues with Eigen 3.3.x.
# If you want to use Eigen vectorization, make sure that you run all the ctests several times, e.g.:
# $ ctest --repeat-until-fail 50
# You might also want to take a look at https://github.com/ufz/ogs/issues/1881.
option(EIGEN_DONT_VECTORIZE "Disables explicit vectorization when defined. Read our cmake config regarding the interplay of this and different Eigen versions!" ON)
```
Maybe you agree...

File: Tests/NumLib/TestComponentNorms.cpp (hunk 1 above)
Comment (endJunction) [inline Tests/NumLib/TestComponentNorms.cpp]: Through the incremental increase this is now at 1700 * eps.

No vectorization also means that intermediate results can be stored (in registers) with 80bit precision, instead of 64 bit when using sse/avx.

File: CMakeLists.txt (hunk 2 above)
Comment (endJunction) [inline CMakeLists.txt]: Agree, but keeping the option's description as it is.

File: Tests/NumLib/TestComponentNorms.cpp (hunk 1 above)
Comment (chleh) [inline Tests/NumLib/TestComponentNorms.cpp]: That sounds sound :smile: (Now the reference solution (computed with Eigen's routines) might use 80 bit at intermediate stages, whereas the component-wise computation only uses the 64 bit double precision everywhere.)

File: CMakeLists.txt [hunk 3]
```diff
@@ -89,6 +89,14 @@ option(OGS_USE_EIGEN "Use Eigen linear solver" ON)
 option(OGS_USE_EIGEN_UNSUPPORTED "Use Eigen unsupported modules" ON)
 option(EIGEN_NO_DEBUG "Disables Eigen's assertions" OFF)
 
+# We assume that it's save to use vectorization with Eigen < 3.3 (strictly smaller than 3.3.!).
+# At least we only observed vectorization issues with Eigen 3.3.x.
+# If you want to use Eigen vectorization, make sure that you run all the ctests several times, e.g.:
+# $ ctest --repeat-until-fail 50
+# You might also want to take a look at https://github.com/ufz/ogs/issues/1881.
+# Please see our cmake config files regarding the interplay of this and different Eigen versions!
```
Comment (chleh) [inline CMakeLists.txt]: Thanks for adopting the comment. But IMHO the last line can be dropped now, since the one reading this comment has already dug into our cmake config, obviously.

**Comment by chleh** [comment]
Once it runs: :+1:

**Comment by chleh** [comment]
Btw: What about the "How to: Performance tweaking" ?

**Comment by endJunction** [comment]
@chleh @fparisio Now the tests seems to pass. I'd like to ask you to test this on the local machines especially for the test cases where this caused problems before.

**Comment by chleh** [comment]
For me the ctests now run. Please answer my two comments about
* performance how to
* the comment in the CMakeLists.txt
Then feel free to merge from my side (maybe after review by second person.). :+1:

@fparisio is on vacation this week AFAIK, so I think we should merge this without him having tested this PR, yet.

Further comment: Some of the ctests are very sensitive towards the number of OpenMP threads when solved with LIS, e.g., they fail with one thread, but succeed with either two or three threads.

**Comment by endJunction** [comment]
https://github.com/ufz/ogs/wiki/Performance-tweaking

**Comment by endJunction** [comment]
@fparisio will test it in two weeks time.
